#!/bin/bash
#SBATCH --gpus-per-node=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=32
#SBATCH --ntasks 1
#SBATCH --ntasks-per-node=1
#SBATCH --time=16:00:00

# This experiment runs first:
srun --export=ALL python3 /home/hice1/[your info]/fl-repo/main.py --seed=1 --partition_method="dirichlet" --partition_alpha=0.1 --n_rounds=200 --batch_size=50 --n_clients=100 --root='path-to-dataset' --dataset_name='cifar10' --model_name='fedavg_cifar' --base_folder='path-to-results-folder' --root_path='path-to-your-FL-repo' --sample_ratio=0.1 --date='enter-date-here' --config_path="/config/fedavg.json"
# This next experiment will immediately run after the first one completes:
srun --export=ALL python3 /home/hice1/[your info]/fl-repo/main.py --seed=1 --partition_method="dirichlet" --partition_alpha=0.1 --n_rounds=200 --batch_size=50 --n_clients=100 --root='path-to-dataset' --dataset_name='cifar10' --model_name='fedavg_cifar' --base_folder='path-to-results-folder' --root_path='path-to-your-FL-repo' --sample_ratio=0.1 --date='enter-date-here' --config_path="/config/fedavg.json"
# Utilize bash scripts so that you don't manually have to set experiments to run.